# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 09:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='\u6807\u9898')),
                ('text', models.TextField(verbose_name='\u5185\u5bb9')),
                ('video', models.FileField(upload_to=b'./upload', verbose_name='\u89c6\u9891')),
            ],
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='\u76ee\u5f55\u540d\u79f0')),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Article'),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.AddField(
            model_name='article',
            name='catelog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Catalog', verbose_name='\u6240\u5c5e\u76ee\u5f55'),
        ),
    ]
