# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 10:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_auto_20160520_0922'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '\u6587\u7ae0', 'verbose_name_plural': '\u6587\u7ae0'},
        ),
        migrations.AlterModelOptions(
            name='catalog',
            options={'verbose_name': '\u76ee\u5f55', 'verbose_name_plural': '\u76ee\u5f55'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': '\u56fe\u7247', 'verbose_name_plural': '\u56fe\u7247'},
        ),
    ]
