# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-22 00:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_auto_20160520_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='catelog',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='page.Catalog', verbose_name='\u6240\u5c5e\u76ee\u5f55'),
        ),
        migrations.AlterField(
            model_name='article',
            name='video',
            field=models.FileField(blank=True, upload_to=b'./upload', verbose_name='\u89c6\u9891'),
        ),
    ]
